# Generated by Django 3.2.5 on 2021-07-24 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='doctor_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='documents.doctor'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='next_visit',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ مراجعه بعدی'),
        ),
    ]
