# Generated by Django 3.2.5 on 2021-07-26 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('documents', '0004_auto_20210724_2306'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctor',
            unique_together={('name', 'patient')},
        ),
    ]
