# Generated by Django 3.2.5 on 2021-07-28 11:26

from django.db import migrations, models
import django.db.models.deletion
import documents.uploaders
import documents.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('documents', '0005_alter_doctor_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField(verbose_name='تاریخ آزمایش')),
                ('file', models.FileField(upload_to=documents.uploaders.test_document_uploader, validators=[documents.validators.validate_file_extension], verbose_name='فایل آزمایش')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='accounts.patient')),
            ],
        ),
    ]
