# Generated by Django 3.2.5 on 2021-07-28 17:06

from django.db import migrations, models
import django.db.models.deletion
import documents.uploaders
import documents.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('documents', '0006_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'آزمایش', 'verbose_name_plural': 'آزمایش ها'},
        ),
        migrations.CreateModel(
            name='OtherDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('sono', 'سونوگرافی'), ('img_scan', 'عکس'), ('others', 'غیره')], max_length=10, verbose_name='نوع سند')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('file', models.FileField(upload_to=documents.uploaders.other_doc_uploader, validators=[documents.validators.validate_file_extension], verbose_name='فایل سند')),
                ('doc_date', models.DateField(verbose_name='تاریخ انجام')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='accounts.patient')),
            ],
        ),
    ]
