# Generated by Django 3.2.5 on 2021-07-29 10:23

from django.db import migrations, models
import documents.uploaders


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_auto_20210728_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=documents.uploaders.prescription_img_uploader, verbose_name='تصویر نسخه'),
        ),
    ]
